-- Riyaziyyat Təlim Platforması - Seed Data
-- Bu fayl verilənlər bazasına ilkin dərs məlumatlarını əlavə edir
-- movzular.txt faylından götürülmüş 10 əsas mövzu

-- MÖVZU 1: Kvadratik Funksiya və Onun Qrafiki
INSERT INTO lessons (title, content, animation_type, animation_config, lesson_order) VALUES (
  'Kvadratik Funksiya və Onun Qrafiki',
  E'# Kvadratik Funksiya və Onun Qrafiki\n\n## Kurikulum Konteksti\n9-cu sinif, III Bölmə - Funksiyalar və Qrafiklər\n\n## Giriş\n\nKvadratik funksiya riyaziyyatın ən maraqlı və praktik mövzularından biridir. Bu funksiya **y = ax² + bx + c** şəklində yazılır, burada a, b və c əmsallardır və **a ≠ 0** olmalıdır.\n\n### Parabolanın Forması\n\n- **a > 0** olarsa → parabola yuxarı açılır (gülümsəyən üz 😊)\n- **a < 0** olarsa → parabola aşağı açılır (kədərli üz ☹️)\n\n### Təpə Nöqtəsi (Vertex)\n\nFunksiyanın ən yüksək və ya ən aşağı nöqtəsinə təpə nöqtəsi deyilir.\n\n**Düstur:** x = -b/(2a)\n\n### Vertex Forması\n\ny = a(x - m)² + n formasında yazdıqda, **(m, n)** təpə nöqtəsinin koordinatlarını birbaşa görürük.\n\n### Diskriminant\n\nParabola ox ilə kəsişmə nöqtələri diskriminantla tapılır:\n\n**D = b² - 4ac**\n\n- **D > 0** → 2 kəsişmə nöqtəsi\n- **D = 0** → 1 kəsişmə (toxunma)\n- **D < 0** → kəsişmə yoxdur\n\n## Real Həyatda İstifadə\n\n- 🏀 Top atanda onun yolu parabola şəklində olur\n- 🌉 Körpülərin qövsləri\n- 🚗 Avtomobil fənərinin işığının yayılması\n- 💼 Biznes: mənfəət-xərc hesablamaları\n\n## Nümunə Məsələ\n\n**Məsələ:** y = 2x² - 8x + 6 funksiyasının qrafikini qurun və təpə nöqtəsini tapın.\n\n### Həll:\n\n1. Əmsallar: a = 2, b = -8, c = 6\n2. Təpə nöqtəsi x-koordinatı: xᵥ = -b/(2a) = -(-8)/(2×2) = 8/4 = 2\n3. Təpə nöqtəsi y-koordinatı: yᵥ = 2(2)² - 8(2) + 6 = 8 - 16 + 6 = -2\n4. **Təpə nöqtəsi: (2, -2)**\n5. Y-kəsişmə: (0, 6)\n6. Diskriminant: D = 64 - 48 = 16 > 0\n7. X-kəsişmələr: (1, 0) və (3, 0)\n\n**Nəticə:** a = 2 > 0 olduğundan parabola yuxarı açılır, minimum nöqtəsi (2, -2)-dir.\n\n## Ev Tapşırıqları\n\n1. Futbol oyunçusu topu 20 m/s sürətlə 45° bucaq altında vurur. Topun yolu h(t) = -5t² + 14t + 2 funksiyası ilə verilir. Maksimum yüksəkliyi tapın.\n\n2. Evinizin yaxınlığında qövsşəkilli tikili tapın və parabolanın tənliyini müəyyənləşdirin.',
  'quadratic-function',
  '{"initialA": 1, "initialB": 0, "initialC": 0, "minA": -5, "maxA": 5, "minB": -10, "maxB": 10, "minC": -10, "maxC": 10}'::jsonb,
  1
);

-- MÖVZU 2: Xətti Tənliklər Sistemi
INSERT INTO lessons (title, content, animation_type, animation_config, lesson_order) VALUES (
  'Xətti Tənliklər Sistemi',
  E'# Xətti Tənliklər Sistemi\n\n## Kurikulum Konteksti\n9-cu sinif, V Bölmə - Tənliklər və Tənliklər Sistemi\n\n## Nə üçün lazımdır?\n\nReal həyatda çox zaman bir deyil, bir neçə naməlumu eyni vaxtda tapmaq lazım gəlir.\n\n**Məsələn:** Mağazada alma və armudun qiymətini bilmirsinizsə, amma iki müxtəlif alışın ümumi qiymətini bilirsinizsə, sistem qurub həll edə bilərsiniz!\n\n## İki Dəyişənli Sistem\n\n```\na₁x + b₁y = c₁\na₂x + b₂y = c₂\n```\n\n## Həll Üsulları\n\n### 1. Əvəzetmə Üsulu\nBir tənlikdən bir dəyişəni ifadə edib digər tənliyə əvəz edirik.\n\n### 2. Toplama (Cəmləmə) Üsulu\nTənlikləri elə vururuq ki, toplayan zaman bir dəyişən yox olsun.\n\n### 3. Qrafik Üsulu\nHər iki tənliyin qrafikini çəkib kəsişmə nöqtəsini tapırıq.\n\n## Sistemin Həll Növləri\n\n- **Tək həll** → İki düz xətt bir nöqtədə kəsişir ✓\n- **Sonsuz həll** → İki düz xətt üst-üstə düşür ∞\n- **Həll yoxdur** → İki düz xətt paraleldir ∥\n\n## Nümunə Məsələ\n\n**Məsələ:** Kitabxanada 3 qələm və 2 dəftər 5 manat, 2 qələm və 5 dəftər 8 manat başa gəlir. Bir qələmin və bir dəftərin qiymətini tapın.\n\n### Həll:\n\n1. Dəyişənlər: x = qələm, y = dəftər\n2. Sistem:\n   - 3x + 2y = 5 ... (1)\n   - 2x + 5y = 8 ... (2)\n3. (1) × 2: 6x + 4y = 10\n4. (2) × 3: 6x + 15y = 24\n5. Çıxırıq: 11y = 14 → y = 14/11 ≈ 1.27 manat\n6. x = 9/11 ≈ 0.82 manat\n\n**Cavab:** Qələm 0.82 manat, dəftər 1.27 manat\n\n## Ev Tapşırıqları\n\n1. Sizdə 20 manat var. Çörək 0.80 manat, süd 2 manat. 15 məhsul almaq istəyirsiniz və bütün pulunuzu xərcləməlisiniz. Neçə çörək və neçə süd ala bilərsiniz?\n\n2. Zavod gündə A və B tipli məhsul istehsal edir. Maksimum istehsal həcmini hesablayın.',
  'linear-system',
  '{"gridRange": 10, "showAnimatedSolution": true}'::jsonb,
  2
);

-- MÖVZU 3: Çevrə və Onun Xassələri
INSERT INTO lessons (title, content, animation_type, animation_config, lesson_order) VALUES (
  'Çevrə və Onun Xassələri',
  E'# Çevrə və Onun Xassələri\n\n## Kurikulum Konteksti\n9-cu sinif, II Bölmə - Çevrə\n\n## Çevrə Nədir?\n\nÇevrə - müəyyən nöqtədən (mərkəzdən) eyni məsafədə olan nöqtələrin çoxluğudur.\n\n### Əsas Elementlər\n\n- **Radius (r)** - mərkəzdən çevrəyə qədər məsafə\n- **Diametr (d)** - radiusun 2 qatı: d = 2r\n- **Çevrənin uzunluğu** - C = 2πr\n- **Sahə** - S = πr²\n\n## Əsas Anlayışlar\n\n### 1. Mərkəzi Bucaq\nTəpəsi çevrənin mərkəzində olan bucaq.\n\n**Xassə:** Mərkəzi bucaq ona söykənən qövsə bərabərdir.\n\n### 2. Daxilə Çəkilmiş Bucaq\nTəpəsi çevrə üzərində olan bucaq.\n\n**Xassə:** Daxilə çəkilmiş bucaq ona söykənən qövsün yarısına bərabərdir.\n\n### 3. Vətər\nÇevrə üzərində iki nöqtəni birləşdirən parça. Ən böyük vətər diametrdir.\n\n### 4. Toxunan\nÇevrəyə yalnız bir nöqtədə toxunan düz xətt.\n\n**Əsas Teorem:** Toxunan həmişə radiusa perpendikulyardır (90°).\n\n## Nümunə Məsələ\n\n**Məsələ:** Radiusu 5 sm olan çevrədə AB vətəri 8 sm-dir. Çevrənin mərkəzindən AB vətərinə qədər məsafəni tapın.\n\n### Həll:\n\n1. Mərkəzdən vətərə perpendikulyar vətəri yarıya bölür\n2. AH = 8/2 = 4 sm\n3. Pifaqor teoremi: OA² = OH² + AH²\n4. 5² = OH² + 4²\n5. 25 = OH² + 16\n6. OH = 3 sm\n\n**Cavab:** Məsafə 3 sm-dir.\n\n## Ev Tapşırıqları\n\n1. Evinizə dairəvi bir əşya götürün və mərkəzini tapın (vətərlər çəkib orta perpendikulyarların kəsişməsini tapın).\n\n2. Üçbucaq şəkilli parka ən böyük dairəvi hovuz salmaq lazımdır. Radiusu hesablayın.',
  'circle-properties',
  '{"showCentralAngle": true, "showInscribedAngle": true, "showTangent": true, "interactive": true}'::jsonb,
  3
);

-- MÖVZU 4: Triqonometriya - Düzbucaqlı Üçbucaqda Nisbətlər
INSERT INTO lessons (title, content, animation_type, animation_config, lesson_order) VALUES (
  'Triqonometriya - Düzbucaqlı Üçbucaqda Nisbətlər',
  E'# Triqonometriya\n\n## Kurikulum Konteksti\n10-cu sinif - Vektorlar və Triqonometrik Nisbətlər\n\n## Triqonometriya Nədir?\n\nYunan dilindən tərcümədə "üçbucaq ölçmə". Bu, bucaqlar və tərəflər arasındakı əlaqəni öyrənən riyaziyyat bölməsidir.\n\n### Harada İstifadə Olunur?\n\n- 🏗️ Binalar, körpülər tikməkdə\n- 📱 GPS naviqasiyasında\n- 🌌 Astronomiyada\n- 🎵 Musiqi dalğalarının təhlilində\n- 🏥 Tibbi görüntüləmədə (MRT, CT)\n\n## Əsas Triqonometrik Nisbətlər\n\nDüzbucaqlı üçbucaqda α bucağı üçün:\n\n### Sinus\n**sin α = qarşı tərəf / hipotenuz**\n\n### Kosinus\n**cos α = bitişik tərəf / hipotenuz**\n\n### Tangens\n**tg α = qarşı tərəf / bitişik tərəf = sin α / cos α**\n\n## Əsas Bucaqlar Cədvəli\n\n| Bucaq | 0° | 30° | 45° | 60° | 90° |\n|-------|----|----|----|----|----|\n| sin | 0 | 1/2 | √2/2 | √3/2 | 1 |\n| cos | 1 | √3/2 | √2/2 | 1/2 | 0 |\n| tg | 0 | 1/√3 | 1 | √3 | ∞ |\n\n## Pifaqor Eyniİiyi\n\n**sin²α + cos²α = 1**\n\n## Nümunə Məsələ\n\n**Məsələ:** 30 m hündürlükdə televiziya qülləsinin təpəsindən müşahidəçiyə məsafə 50 m-dir. Baxış bucağını tapın.\n\n### Həll:\n\n1. sin α = qarşı/hipotenuz = 30/50 = 0.6\n2. α = arcsin(0.6) ≈ 36.87°\n3. **Cavab:** Təqribən 37°\n\n## Ev Tapşırıqları\n\n1. Nərdivanın uzunluğu 5 m, divara 60° bucaq altında söykənir. Nərdivan divarın hansı hündürlüyünə çatır?\n\n2. Təhlükəsiz məsafədən ağacın hündürlüyünü ölçün.',
  'trigonometry',
  '{"angleRange": [0, 90], "showUnitCircle": true, "showValues": true}'::jsonb,
  4
);

-- MÖVZU 5: Rasional Tənliklər və Məsələ Həlli
INSERT INTO lessons (title, content, animation_type, animation_config, lesson_order) VALUES (
  'Rasional Tənliklər və Məsələ Həlli',
  E'# Rasional Tənliklər\n\n## Kurikulum Konteksti\n9-cu sinif, V Bölmə - Tənliklər və Tənliklər Sistemi\n\n## Rasional Tənliklər Nədir?\n\nKəsrləri olan tənliklərdir - dəyişən məxrəcdə (payın altında) yerləşir.\n\n**Məsələn:** 3/x + 2/(x-1) = 5\n\n## Həll Addımları\n\n### Addım 1: Məhdudiyyətləri Tapın\nMəxrəc 0 ola bilməz!\n\n### Addım 2: Ümumi Məxrəc\nBütün tənliyi ümumi məxrəcə vurun.\n\n### Addım 3: Həll Edin və Yoxlayın\nCavabı məhdudiyyətlərə görə yoxlayın.\n\n## DİQQƏT!\n\nƏn çox səhv: Məxrəc sıfır olursa, həll düzgün deyil və kənarlaşdırmalıyıq!\n\n## Real Həyatda\n\n- İki işçi birlikdə işi neçə günə bitirər?\n- Çay axınına qarşı və axınla getmə\n- Boru ilə hovuzun dolması\n\n### Tipik Düstur\n**1/a + 1/b = 1/c**\n\nBu düstur demək istəyir: A-nın bir gündə gördüyü iş 1/a, B-ninki 1/b, birgə görəcəkləri 1/c.\n\n## Nümunə Məsələ\n\n**Məsələ:** Ali hovuzu 6 saata, Vəli 4 saata doldura bilir. Birlikdə neçə saata dolarlar?\n\n### Həll:\n\n1. Ali bir saatda: 1/6 hissəsini doldurur\n2. Vəli bir saatda: 1/4 hissəsini doldurur\n3. Birlikdə: 1/6 + 1/4 = 1/x\n4. 2/12 + 3/12 = 1/x\n5. 5/12 = 1/x\n6. x = 12/5 = 2.4 saat = 2 saat 24 dəqiqə\n\n**Cavab:** 2 saat 24 dəqiqə\n\n## Ev Tapşırıqları\n\n1. Hovuzun dolması üçün 2 boru var. Birinci 3 saata doldurur, ikinci 6 saata boşaldır. Hər iki boru açıq olsa nə olacaq?\n\n2. Velosipedçinin yol məsələsini həll edin.',
  'rational-equations',
  '{"showWorkAnimation": true, "numberOfWorkers": 2}'::jsonb,
  5
);

-- MÖVZU 6: Ədədi Silsilələr
INSERT INTO lessons (title, content, animation_type, animation_config, lesson_order) VALUES (
  'Ədədi Silsilələr (Arifmetik və Həndəsi)',
  E'# Ədədi Silsilələr\n\n## Kurikulum Konteksti\n9-cu sinif, IX Bölmə - Ədədi Ardıcıllıqlar\n\n## Nə üçün Vacibdir?\n\nTəbiətdə, biznes dünyasında, texnologiyada hər yerdə ardıcıllıqlar var:\n- 💰 Bank əmanətlərindəki faizlər\n- 📈 Nüfusun artımı\n- 🦠 Virusun yayılması\n- ♟️ Şahmat lövhəsindəki dənələr\n\n## 1. Ədədi (Arifmetik) Silsilə\n\nHər hədd əvvəlki hədddən eyni ədəd (diferens) qədər fərqlənir.\n\n### Ümumi Hədd\n**aₙ = a₁ + (n-1)d**\n\nBurada:\n- aₙ = n-ci hədd\n- a₁ = birinci hədd\n- d = diferens\n- n = həddin nömrəsi\n\n### İlk n Həddin Cəmi\n**Sₙ = n(a₁ + aₙ)/2**\n\n**Nümunə:** 2, 5, 8, 11, 14, ... (d = 3)\n\n## 2. Həndəsi Silsilə\n\nHər hədd əvvəlki həddi eyni ədədə (məxrəc) vurduqda alınır.\n\n### Ümumi Hədd\n**bₙ = b₁ · qⁿ⁻¹**\n\nBurada:\n- bₙ = n-ci hədd\n- b₁ = birinci hədd\n- q = məxrəc\n\n### İlk n Həddin Cəmi\n**Sₙ = b₁(qⁿ - 1)/(q - 1)**\n\n### Sonsuz Cəm (|q| < 1)\n**S∞ = b₁/(1 - q)**\n\n**Nümunə:** 3, 6, 12, 24, 48, ... (q = 2)\n\n## Nümunə Məsələ 1\n\n**Məsələ:** Ali hər gün kitab oxuyur. Birinci gün 5 səhifə, ikinci gün 8, üçüncü gün 11 səhifə. 30 gün ərzində cəmi neçə səhifə oxuyacaq?\n\n### Həll:\n\n1. d = 3, a₁ = 5, n = 30\n2. a₃₀ = 5 + 29×3 = 92 səhifə\n3. S₃₀ = 30(5 + 92)/2 = 1455 səhifə\n\n## Nümunə Məsələ 2\n\n**Məsələ:** Video paylaşırsınız. Birinci gün 3 nəfər, hər gün 2 qat artır. 10-cu gün neçə nəfər baxar?\n\n### Həll:\n\n1. q = 2, b₁ = 3, n = 10\n2. b₁₀ = 3 × 2⁹ = 3 × 512 = 1536 nəfər\n3. Cəmi: 3069 nəfər\n\n## Ev Tapşırıqları\n\n1. Bankda 1000 manat əmanət açırsınız. İllik 8% faiz. 10 il sonra nə qədər olacaq?\n\n2. Şahmat lövhəsi əfsanəsi: 64 xanalı lövhəni buğda dənəsi ilə doldurmaq.',
  'sequences',
  '{"arithmeticMode": true, "geometricMode": true, "maxTerms": 15}'::jsonb,
  6
);

-- MÖVZU 7: Çoxhədlilər və Vuruqlara Ayırma
INSERT INTO lessons (title, content, animation_type, animation_config, lesson_order) VALUES (
  'Çoxhədlilər və Vuruqlara Ayırma',
  E'# Çoxhədlilər və Vuruqlara Ayırma\n\n## Kurikulum Konteksti\n11-ci sinif, I Bölmə - Çoxhədlilər\n\n## Çoxhədli Nədir?\n\nBir  neçə həddin toplandığı cəbri ifadədir.\n\n**Məsələn:** P(x) = 3x³ - 5x² + 2x - 7\n\n**Dərəcə:** Ən böyük dərəcəli həddin dərəcəsi (yuxarıdakı nümunədə 3)\n\n## Vuruqlara Ayırma\n\nÇoxhədlini vuruqların hasili şəklində yazmaq.\n\n**Nümunə:** x² - 5x + 6 = (x - 2)(x - 3)\n\n## Vuruqlara Ayırma Üsulları\n\n### 1. Ümumi Vuruq\n6x³ - 9x² = 3x²(2x - 3)\n\n### 2. Qısa Vurma Düsturları\n\n- (a + b)² = a² + 2ab + b²\n- (a - b)² = a² - 2ab + b²\n- a² - b² = (a - b)(a + b)\n- a³ + b³ = (a + b)(a² - ab + b²)\n- a³ - b³ = (a - b)(a² + ab + b²)\n\n### 3. Qruplaşdırma\nx³ + x² + x + 1 = x²(x + 1) + 1(x + 1) = (x + 1)(x² + 1)\n\n### 4. Kök Tapma\n\nƏgər P(a) = 0 olarsa, (x - a) vuruqdur.\n\n## Bezout Teoremi\n\nP(x) çoxhədlisini (x - a)-ya bölməyədən qalıq P(a)-ya bərabərdir.\n\n## Rasional Köklərin Tapılması\n\nƏgər p/q rasional kökdirsə:\n- p - sərbəst həddin bölənlərindəndir\n- q - aparıcı əmsalın bölənlərindəndir\n\n## Nümunə Məsələ\n\n**Məsələ:** x³ + 2x² - 5x - 6 çoxhədlisini vuruqlara ayırın.\n\n### Həll:\n\n1. Mümkün kökləri: ±1, ±2, ±3, ±6\n2. P(-1) = -1 + 2 + 5 - 6 = 0 ✓ Kök!\n3. Horner sxemi ilə (x + 1)-ə böldük\n4. P(x) = (x + 1)(x² + x - 6)\n5. x² + x - 6 = (x - 2)(x + 3)\n6. **Cavab:** (x + 1)(x - 2)(x + 3)\n\n**Kökləri:** x₁ = -1, x₂ = 2, x₃ = -3\n\n## Ev Tapşırıqları\n\n1. Vuruqlara ayırın:\n   - a) x³ - 7x + 6\n   - b) x⁴ - 1\n   - c) x³ + 3x² - 4\n\n2. Düzbucaqlının uzunluğu enindən 3 sm çox, sahəsi 180 sm². Ölçülərini tapın.',
  'polynomial-factorizer',
  '{"showHornerScheme": true, "showGraph": true, "maxDegree": 4}'::jsonb,
  7
);

-- MÖVZU 8: Törəmə və Funksiyaların Tədqiqi
INSERT INTO lessons (title, content, animation_type, animation_config, lesson_order) VALUES (
  'Törəmə və Funksiyaların Tədqiqi',
  E'# Törəmə və Funksiyaların Tədqiqi\n\n## Kurikulum Konteksti\n11-ci sinif, V və VII Bölmələr - Törəmə və Onun Tətbiqi\n\n## Törəmə Nədir?\n\nFunksiyanın dəyişmə sürətini göstərən riyazi alətdir.\n\n### Fizikada\n- Sürət = məsafənin törəməsi\n- Təcil = sürətin törəməsi\n\n### İqtisadiyyatda\n- Marjinal məsrəf\n- Mənfəətin dəyişməsi\n\n## Törəmənin Həndəsi Mənası\n\n**f\'(x₀)** - funksiyanın x₀ nöqtəsindəki toxunanının meyl əmsalıdır.\n\n## Əsas Törəmə Düsturları\n\n- (c)\' = 0 (sabitin törəməsi)\n- (x)\' = 1\n- (xⁿ)\' = nxⁿ⁻¹ (qüvvət düsturu)\n- (sin x)\' = cos x\n- (cos x)\' = -sin x\n- (eˣ)\' = eˣ\n- (ln x)\' = 1/x\n\n## Törəmə Qaydaları\n\n- (f + g)\' = f\' + g\' (toplama)\n- (f × g)\' = f\'g + fg\' (hasilin törəməsi)\n- (f/g)\' = (f\'g - fg\')/g² (nisbətin törəməsi)\n- (f(g(x)))\' = f\'(g(x)) × g\'(x) (mürəkkəb funksiya)\n\n## Törəmənin Tətbiqi\n\n### 1. Artma/Azalma\n\n- f\'(x) > 0 → funksiya artan\n- f\'(x) < 0 → funksiya azalan\n- f\'(x) = 0 → mümkün ekstremum\n\n### 2. Ekstremumlar\n\nMaksimum/minimum nöqtələr f\'(x) = 0 tənliyinin köklərindən tapılır.\n\n### 3. Optimallaşdırma\n\nMaksimum mənfəət, minimum məsrəf, minimum material.\n\n## Nümunə Məsələ\n\n**Məsələ:** f(x) = x³ - 6x² + 9x + 1 funksiyasının ekstremumlarını tapın.\n\n### Həll:\n\n1. f\'(x) = 3x² - 12x + 9\n2. f\'(x) = 0: 3x² - 12x + 9 = 0\n3. x² - 4x + 3 = 0\n4. (x - 1)(x - 3) = 0\n5. x₁ = 1, x₂ = 3\n6. İşarə sxemi:\n   - x < 1: f\' > 0 (artan)\n   - 1 < x < 3: f\' < 0 (azalan)\n   - x > 3: f\' > 0 (artan)\n7. f(1) = 5 (maksimum)\n8. f(3) = 1 (minimum)\n\n**Cavab:**\n- Artma: (-∞, 1) və (3, +∞)\n- Azalma: (1, 3)\n- Maksimum: (1, 5)\n- Minimum: (3, 1)\n\n## Ev Tapşırıqları\n\n1. Cisim s(t) = t³ - 9t² + 24t qanunu ilə hərəkət edir. Maksimum sürəti tapın.\n\n2. Şirkət mənfəəti P(x) = -2x² + 40x - 150. Maksimum mənfəəti və istehsal həcmini tapın.',
  'derivative-explorer',
  '{"functions": ["x^2", "x^3-3x", "sin(x)"], "showTangent": true, "showDerivative": true}'::jsonb,
  8
);

-- MÖVZU 9: Ehtimal və Statistika
INSERT INTO lessons (title, content, animation_type, animation_config, lesson_order) VALUES (
  'Ehtimal və Statistika Əsasları',
  E'# Ehtimal və Statistika\n\n## Kurikulum Konteksti\n9-cu sinif, X Bölmə - Məlumatın Təqdimi, Birlişmələr, Ehtimal\n\n## Müasir Həyatda Əhəmiyyəti\n\n- 🌦️ Hava proqnozu ("40% ehtimalla yağış")\n- 🦠 COVID-19 testlərinin dəqiqliyi\n- 📊 Seçkilərdə sosiologiya\n- 💊 Tibbdə dərman təsirinin qiymətləndirilməsi\n\n## Əsas Anlayışlar\n\n### Təsadüfi Hadisə\n\nBaş verə və ya verməyə bilən hadisə.\n\n- **Mümkün hadisə:** zər atanda 6 gəlməsi\n- **Mümkün olmayan:** zər atanda 7 gəlməsi\n- **Mütləq hadisə:** zər atanda 1-6 arası rəqəm\n\n### Ehtimal\n\n**P(A) = (əlverişli nəticələr) / (bütün mümkün nəticələr)**\n\n0 ≤ P(A) ≤ 1\n\n## Statistik Göstəricilər\n\n### Orta (Mean)\nBütün qiymətlərin cəminin sayına nisbəti.\n\n### Mediana (Median)\nSıralanmış verilənlərin ortadakı qiyməti.\n\n### Moda (Mode)\nƏn çox təkrarlanan qiymət.\n\n### Amplituda (Range)\nMaksimum - Minimum\n\n## Birlişmələr\n\n### Permutasiya\nn elementinin sıralaması:\n**Pₙ = n! = n × (n-1) × ... × 2 × 1**\n\n### Kombinasiya\nn elementdən k-nı seçmək:\n**Cₙᵏ = n! / [k!(n-k)!]**\n\n## Nümunə Məsələ\n\n**Məsələ:** Zər və sikkə eyni vaxtda atılır. "Zərdə 4 və sikkədə Tura" hadisəsinin ehtimalını tapın.\n\n### Həll:\n\n1. Zər: 6 nəticə, Sikkə: 2 nəticə\n2. Ümumi: 6 × 2 = 12 nəticə\n3. Əlverişli: (4, T) - yalnız 1\n4. P = 1/12 ≈ 8.33%\n\n**Alternativ:** P(4) × P(T) = (1/6) × (1/2) = 1/12\n\n## Ev Tapşırıqları\n\n1. 49 topdan 6-sını çəkən lotoreyada qalib olmaq ehtimalı nədir?\n\n2. Sinifinizdəki 20 şagirdin telefonda xərclədiyi vaxtı toplayın. Orta, mediana, moda hesablayın.',
  'probability-simulator',
  '{"diceCount": 1, "coinCount": 1, "maxRolls": 1000, "showHistogram": true}'::jsonb,
  9
);

-- MÖVZU 10: Bərabərsizliklər
INSERT INTO lessons (title, content, animation_type, animation_config, lesson_order) VALUES (
  'Bərabərsizliklər və İntervallar Üsulu',
  E'# Bərabərsizliklər və İntervallar Üsulu\n\n## Kurikulum Konteksti\n9-cu sinif, VII Bölmə - Bərabərsizliklər\n\n## Nə üçün Vacibdir?\n\nReal həyatda tənliklərdən daha çox işlədilir!\n\n**Məsələlər:**\n- "Balansınız 50 manatdan çox olmalıdır" → x > 50\n- "Lift maksimum 500 kq daşıya bilər" → x ≤ 500\n- "Temperatur 18-25°C arasında" → 18 ≤ T ≤ 25\n\n## Əsas Bərabərsizlik Növləri\n\n### 1. Xətti\n2x + 5 < 13\n\n### 2. Kvadrat\nx² - 5x + 6 > 0\n\n### 3. Rasional\n(x - 2)/(x + 3) ≥ 0\n\n## Həll Üsulları\n\n### Üsul 1: Cəbri (xətti üçün)\n2x + 5 < 13\n2x < 8\nx < 4\n\n### Üsul 2: Qrafik\nFunksiyaların qrafiklərini çəkib kəsişmə tapırıq.\n\n### Üsul 3: İntervallar Üsulu\n\n1. Bərabərsizliyi sıfıra bərabər edirik\n2. Kökləri tapırıq\n3. Ədəd oxunda intervalları qeyd edirik\n4. Hər intervalda işarəni yoxlayırıq\n\n## Kvadrat Bərabərsizlik Nümunəsi\n\n**Məsələ:** x² - 5x + 6 > 0\n\n### Həll:\n\n1. x² - 5x + 6 = 0\n2. (x - 2)(x - 3) = 0\n3. x₁ = 2, x₂ = 3\n4. İntervallar:\n   - x < 2: (+) ✓\n   - 2 < x < 3: (-) ✗\n   - x > 3: (+) ✓\n5. **Cavab:** x ∈ (-∞, 2) ∪ (3, +∞)\n\n## Rasional Bərabərsizlik\n\n**Məsələ:** (x - 2)/(x + 3) ≥ 0\n\n### Həll:\n\n1. Pay: x - 2 = 0 → x = 2\n2. Məxrəc: x + 3 = 0 → x = -3 (məhdudiyyət!)\n3. İşarə sxemi:\n   - x < -3: (-)\n   - -3 < x < 2: (-)\n   - x > 2: (+)\n4. ≥ 0 üçün: (+) və ya sıfır\n5. **Cavab:** x ∈ (-∞, -3) ∪ [2, +∞)\n\nNOT: x = -3 daxil deyil (məxrəc sıfır olar)\n\n## Nümunə Məsələ\n\n**Məsələ:** x² - 7x + 10 ≤ 0\n\n### Həll:\n\n1. x² - 7x + 10 = 0\n2. x₁ = 2, x₂ = 5\n3. (x - 2)(x - 5) ≤ 0\n4. İşarə sxemi:\n   - x < 2: (+)\n   - 2 ≤ x ≤ 5: (-) ✓\n   - x > 5: (+)\n5. **Cavab:** x ∈ [2, 5]\n\n## Ev Tapşırıqları\n\n1. Avtobusda 45 yer var. Bilet 2 manat. Ən azı 60 manat qazanmaq lazımdır. Minimum neçə bilet satmalı?\n\n2. (x² - 9)/(x - 2) > 0 bərabərsizliyini həll edin.',
  'inequality-solver',
  '{"types": ["quadratic", "rational", "system"], "showIntervalMethod": true}'::jsonb,
  10
);
